datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /youtu_fuxi-team2-1/Public_Dataset/TextCaps/train_images
      ann_path: /youtu_fuxi-team2-1/Public_Dataset/TextCaps/TextCaps_0.1_train.json


