datasets:
  ocrvqa:
    data_type: images
    build_info:
      image_path: /youtu_fuxi-team2-1/Public_Dataset/OCR-VQA/OCRVQA/images
      ann_path: /youtu_fuxi-team2-1/Public_Dataset/OCR-VQA/OCRVQA/dataset.json