datasets:
  refcoco:
    data_type: images
    build_info:
      image_path: /youtu_fuxi-team2-1/Public_Dataset/COCO2014/train2014
      ann_path: /youtu_fuxi-team2-1/Public_Dataset/Referring_Expression
      dataset: refcoco
      splitBy: unc