datasets:
  multitask_conversation:
    data_type: images
    build_info:
    
      image_path: /youtu_fuxi-team2-1/Public_Dataset/COCO2014/train2014
      ann_path: /youtu_fuxi-team2-1/Public_Dataset/Multi-task_Conversation/multitask_conversation.json